<?php

/**
 * @file
 * Bootstrap page builder module file.
 */

/**
 * Implements hook_page_attachments().
 */
function acx_bootstrap_page_builder_page_attachments(array &$page) {
  $active_theme = \Drupal::theme()->getActiveTheme();
  $admin_theme = \Drupal::config('system.theme')->get('admin');

  if ($admin_theme !== $active_theme->getName()) {
    $page['#attached']['library'][] = 'acx_bootstrap_page_builder/bootstrap.cdn';
  }
}

/**
 * Implements hook_theme().
 */
function acx_bootstrap_page_builder_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__bp_container' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_row' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_column' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_slider' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_slider_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_carousel' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_numbers' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_number_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_icon_item' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__bp_modal' => [
      'base hook' => 'paragraph',
    ],
    'field__bp_items' => [
      'base hook' => 'field',
    ],
  ];
}
